# Generated by Django 3.2.3 on 2021-07-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_default_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_full_name',
            new_name='default_last_name',
        ),
    ]
