# Generated by Django 3.2.3 on 2021-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
