# Generated by Django 3.2.3 on 2021-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_cart',
            field=models.TextField(blank=True, default=''),
        ),
    ]
