# Generated by Django 3.2.3 on 2021-07-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210714_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_golf_balls',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
