# Generated by Django 3.2.3 on 2021-07-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210630_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_golf_balls',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
