# Generated by Django 3.2.3 on 2021-07-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_email', models.EmailField(max_length=100, unique=True)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
